#!/usr/bin/env python3
"""Generates C# bindings for the iFly 737 MAX SDK from the official headers.

Inputs (SDK v1.5 headers):
  key_command.h   -> IFlyKeyCommand.cs   (enum; values are SEQUENTIAL from 0 — the
                                          C++ enum has no explicit values, so ORDER
                                          IS THE ABI. Never reorder or insert.)
  SDK_Defines.h   -> IFlySdkOffsets.cs   (byte offsets into the pack(8) shared-memory
                                          struct ShareMemory737MAXSDK, computed with
                                          MSVC x64 layout rules: BYTE/char/bool align 1,
                                          int/long align 4, double align 8.)

Usage:  python generate_ifly_sdk.py <sdk_dir> <out_dir>
        sdk_dir must contain key_command.h and SDK_Defines.h.

Re-run whenever iFly ships a new SDK version (struct + enum are append-only).
"""
import re
import sys
import os

TYPE_INFO = {
    # name: (size, align)
    "BYTE": (1, 1),
    "bool": (1, 1),
    "char": (1, 1),
    "int": (4, 4),
    "long": (4, 4),   # MSVC: long is 4 bytes on x64
    "double": (8, 8),
}


def parse_key_commands(path):
    cmds = []
    rx = re.compile(r"^\s*(KEY_COMMAND_[A-Za-z0-9_]+)\s*,(?://(.*))?")
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            m = rx.match(line)
            if m:
                comment = (m.group(2) or "").strip()
                # keep only the human description, drop the ValueN help columns
                comment = re.split(r"\s*Value1:", comment)[0].strip()
                cmds.append((m.group(1), comment))
    return cmds


def parse_struct(path):
    fields = []  # (name, ctype, dims, offset, comment)
    in_struct = False
    offset = 0
    rx = re.compile(
        r"^\s*(BYTE|bool|char|int|long|double)\s+([A-Za-z0-9_]+)"
        r"((?:\[\d+\])*)\s*;(?://(.*))?"
    )
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            if "typedef struct ShareMemory737MAXSDK" in line:
                in_struct = True
                continue
            if in_struct and line.strip().startswith("}"):
                break
            if not in_struct:
                continue
            m = rx.match(line)
            if not m:
                continue
            ctype, name, dims_s, comment = m.group(1), m.group(2), m.group(3), (m.group(4) or "").strip()
            dims = [int(d) for d in re.findall(r"\[(\d+)\]", dims_s)]
            size, align = TYPE_INFO[ctype]
            # pack(8): effective alignment = min(natural, 8); all our types <= 8
            if offset % align:
                offset += align - (offset % align)
            count = 1
            for d in dims:
                count *= d
            fields.append((name, ctype, dims, offset, comment))
            offset += size * count
    return fields, offset


CS_TYPE = {"BYTE": "byte", "bool": "byte", "char": "byte", "int": "int", "long": "int", "double": "double"}


def emit_commands(cmds, out_path):
    lines = [
        "// <auto-generated>",
        "// Generated by tools/ifly-gen/generate_ifly_sdk.py from iFly SDK v1.5 key_command.h.",
        "// Values are SEQUENTIAL and form the wire ABI of the iFly WM_COPYDATA command channel.",
        "// DO NOT reorder, insert, or hand-edit — regenerate from the header instead.",
        "// </auto-generated>",
        "",
        "namespace MSFSBlindAssist.SimConnect.IFly;",
        "",
        "/// <summary>Command IDs for the iFly 737 MAX WM_COPYDATA message channel (KEY_COMMAND_IFLY737MAX).</summary>",
        "public enum IFlyKeyCommand",
        "{",
    ]
    for i, (name, comment) in enumerate(cmds):
        short = name[len("KEY_COMMAND_"):]
        if comment:
            lines.append(f"    /// <summary>{comment.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')}</summary>")
        lines.append(f"    {short} = {i},")
    lines.append("}")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return len(cmds)


def emit_offsets(fields, total, out_path):
    lines = [
        "// <auto-generated>",
        "// Generated by tools/ifly-gen/generate_ifly_sdk.py from iFly SDK v1.5 SDK_Defines.h.",
        "// Byte offsets into the pack(8) ShareMemory737MAXSDK shared-memory struct",
        "// (file mapping \"iFly737MAX_SDK_FileMappingObject\"). MSVC x64 layout:",
        "// BYTE/char/bool = 1 byte, int/long = 4, double = 8; arrays are contiguous.",
        "// DO NOT hand-edit — regenerate from the header instead.",
        "// </auto-generated>",
        "",
        "namespace MSFSBlindAssist.SimConnect.IFly;",
        "",
        "/// <summary>Field offsets (and array dims) for the iFly shared-memory state block.</summary>",
        "public static class IFlySdkOffsets",
        "{",
        f"    /// <summary>Total computed struct size in bytes.</summary>",
        f"    public const int StructSize = {total};",
        "",
    ]
    for (name, ctype, dims, offset, comment) in fields:
        size, _ = TYPE_INFO[ctype]
        cs = CS_TYPE[ctype]
        dims_doc = "".join(f"[{d}]" for d in dims)
        doc = f"{ctype} {name}{dims_doc}"
        if comment:
            doc += " — " + comment.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        lines.append(f"    /// <summary>{doc}</summary>")
        lines.append(f"    public const int {name} = {offset};")
        if dims:
            # element stride helpers for multi-dim arrays (row-major, contiguous)
            strides = []
            acc = size
            for d in reversed(dims):
                strides.insert(0, acc)
                acc *= d
            for di, (d, st) in enumerate(zip(dims, strides)):
                lines.append(f"    public const int {name}_Dim{di} = {d};")
                lines.append(f"    public const int {name}_Stride{di} = {st};")
        lines.append("")
    lines.append("}")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return len(fields)



def emit_fields_table(fields, out_path):
    """Emits the generic per-field diff table used by IFlySdkClient change detection.

    Excludes the bulk display arrays (CDU screens, ELEC LED text) — those are
    handled by dedicated snapshot helpers, not per-field events.
    """
    EXCLUDE = {"LSKChar", "LSK_SmallFont", "LSK_Color", "ELEC_LED_TEXT"}
    lines = [
        "// <auto-generated>",
        "// Generated by tools/ifly-gen/generate_ifly_sdk.py from iFly SDK v1.5 SDK_Defines.h.",
        "// Flat field table for generic change detection. Arrays are flattened row-major",
        "// (event keys get an _i suffix). Kind: 'B' = byte/bool/char, 'I' = int32, 'D' = double.",
        "// DO NOT hand-edit — regenerate from the header instead.",
        "// </auto-generated>",
        "",
        "namespace MSFSBlindAssist.SimConnect.IFly;",
        "",
        "public readonly record struct IFlySdkField(string Name, int Offset, char Kind, int Count, int Stride);",
        "",
        "public static class IFlySdkFields",
        "{",
        "    public static readonly IFlySdkField[] All =",
        "    [",
    ]
    kind_map = {"BYTE": "B", "bool": "B", "char": "B", "int": "I", "long": "I", "double": "D"}
    n = 0
    for (name, ctype, dims, offset, _c) in fields:
        if name in EXCLUDE:
            continue
        size, _ = TYPE_INFO[ctype]
        count = 1
        for d in dims:
            count *= d
        lines.append(f'        new("{name}", {offset}, \'{kind_map[ctype]}\', {count}, {size}),')
        n += 1
    lines += ["    ];", "}"]
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return n


def main():
    sdk_dir, out_dir = sys.argv[1], sys.argv[2]
    os.makedirs(out_dir, exist_ok=True)
    cmds = parse_key_commands(os.path.join(sdk_dir, "key_command.h"))
    fields, total = parse_struct(os.path.join(sdk_dir, "SDK_Defines.h"))
    n_cmd = emit_commands(cmds, os.path.join(out_dir, "IFlyKeyCommand.cs"))
    n_fld = emit_offsets(fields, total, os.path.join(out_dir, "IFlySdkOffsets.cs"))
    n_tab = emit_fields_table(fields, os.path.join(out_dir, "IFlySdkFields.cs"))
    print(f"field table entries: {n_tab}")
    print(f"commands: {n_cmd} (END sentinel included: {'yes' if cmds and cmds[-1][0].endswith('_END') else 'NO'})")
    print(f"fields:   {n_fld}, struct size {total} bytes")
    # sanity spot checks for hand verification
    idx = {f[0]: f for f in fields}
    for probe in ("iFly737MAX_STATE", "Aircraft_Model", "Tick18", "UNITstyle",
                  "ALT_HLD_Switch_Status", "LSKChar", "LSK_SmallFont", "LSK_Color",
                  "CDU_EXEC_Status", "Throttle_Lever_1_Position", "CVR_Switch_Status"):
        if probe in idx:
            f = idx[probe]
            print(f"  {probe}: offset {f[3]} dims {f[2]}")


if __name__ == "__main__":
    main()
