//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBWBA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ScreenReader")]
        public string AnnouncementMode {
            get {
                return ((string)(this["AnnouncementMode"]));
            }
            set {
                this["AnnouncementMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GeoNamesApiUsername {
            get {
                return ((string)(this["GeoNamesApiUsername"]));
            }
            set {
                this["GeoNamesApiUsername"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int NearbyCitiesRange {
            get {
                return ((int)(this["NearbyCitiesRange"]));
            }
            set {
                this["NearbyCitiesRange"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int RegionalCitiesRange {
            get {
                return ((int)(this["RegionalCitiesRange"]));
            }
            set {
                this["RegionalCitiesRange"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("185")]
        public int MajorCitiesRange {
            get {
                return ((int)(this["MajorCitiesRange"]));
            }
            set {
                this["MajorCitiesRange"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int LandmarksRange {
            get {
                return ((int)(this["LandmarksRange"]));
            }
            set {
                this["LandmarksRange"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("miles")]
        public string DistanceUnits {
            get {
                return ((string)(this["DistanceUnits"]));
            }
            set {
                this["DistanceUnits"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int AirportsRange {
            get {
                return ((int)(this["AirportsRange"]));
            }
            set {
                this["AirportsRange"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int TerrainRange {
            get {
                return ((int)(this["TerrainRange"]));
            }
            set {
                this["TerrainRange"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int WaterBodiesRange {
            get {
                return ((int)(this["WaterBodiesRange"]));
            }
            set {
                this["WaterBodiesRange"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int TouristLandmarksRange {
            get {
                return ((int)(this["TouristLandmarksRange"]));
            }
            set {
                this["TouristLandmarksRange"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxNearbyPlacesToShow {
            get {
                return ((int)(this["MaxNearbyPlacesToShow"]));
            }
            set {
                this["MaxNearbyPlacesToShow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxMajorCitiesToShow {
            get {
                return ((int)(this["MaxMajorCitiesToShow"]));
            }
            set {
                this["MaxMajorCitiesToShow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MaxAirportsToShow {
            get {
                return ((int)(this["MaxAirportsToShow"]));
            }
            set {
                this["MaxAirportsToShow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MaxTerrainFeaturesToShow {
            get {
                return ((int)(this["MaxTerrainFeaturesToShow"]));
            }
            set {
                this["MaxTerrainFeaturesToShow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MaxWaterBodiesToShow {
            get {
                return ((int)(this["MaxWaterBodiesToShow"]));
            }
            set {
                this["MaxWaterBodiesToShow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MaxTouristLandmarksToShow {
            get {
                return ((int)(this["MaxTouristLandmarksToShow"]));
            }
            set {
                this["MaxTouristLandmarksToShow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public int MajorCityPopulationThreshold {
            get {
                return ((int)(this["MajorCityPopulationThreshold"]));
            }
            set {
                this["MajorCityPopulationThreshold"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cities15000")]
        public string MajorCityAPIThreshold {
            get {
                return ((string)(this["MajorCityAPIThreshold"]));
            }
            set {
                this["MajorCityAPIThreshold"] = value;
            }
        }
    }
}
