using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using MSFSBlindAssist.Utils.Logging;

namespace MSFSBlindAssist.Aircraft.MD11;

/// <summary>
/// The TFDi MD-11's control surface, deserialized from <c>md11_control_map.json</c>.
///
/// The JSON is generated by <c>tools/md11-gen/generate_md11_map.py</c> straight out of the
/// aircraft's own ModelBehaviorDefs XML plus <c>md11host.wasm</c>, and is checked in so the
/// map is reviewable as data. Regenerate it (rather than hand-editing) whenever TFDi ships a
/// build that moves an event id or renames a node — every label, detent name and switch
/// position in here is TFDi's own wording lifted from their tooltips, not invented by MSFSBA,
/// which is what keeps the screen reader saying what the real cockpit says.
///
/// It ships as an EMBEDDED RESOURCE, not a copied file. The repo's convention for
/// <c>Resources\</c> is a per-file <c>&lt;None Update&gt;</c> + CopyToOutputDirectory (the build
/// does not wildcard-copy that folder), but a missing copied file degrades to an MD-11 with
/// ZERO controls and no obvious cause. Embedding makes that failure impossible.
/// </summary>
public sealed class Md11ControlMap
{
    [JsonPropertyName("controls")]
    public List<Md11Control> Controls { get; set; } = new();

    /// <summary>
    /// TFDi's documented integration surface (Integration Guide → Variables): the read-only
    /// state exports (FCP windows, AP/ATS/APU state, V-speeds, minimums, altimeters, fuel) and
    /// the writable <c>MD11_EXTCTL_*</c> external-control vars. These are NOT clickable controls
    /// and do not appear in <see cref="Controls"/>.
    /// </summary>
    [JsonPropertyName("export_vars")]
    public List<string> ExportVars { get; set; } = new();

    /// <summary>
    /// Control-table vars that no ModelBehaviorDefs control references — animation ranges
    /// (<c>_RNG</c>), exterior states, and the FCP push/pull latch vars. Kept for reference;
    /// MSFSBA does not register them wholesale.
    /// </summary>
    [JsonPropertyName("state_only_vars")]
    public List<string> StateOnlyVars { get; set; } = new();

    private static readonly JsonSerializerOptions Options = new()
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true,
    };

    private static Md11ControlMap? _cached;

    /// <summary>
    /// Loads (and memoizes) the embedded control map. Returns an EMPTY map rather than throwing
    /// if the resource is missing or malformed: a broken map must degrade to "MD-11 with no
    /// panels" — annoying but survivable, and loudly logged — never to an unhandled exception on
    /// the aircraft-switch path, which would take the whole app down with it.
    /// </summary>
    public static Md11ControlMap Load()
    {
        if (_cached != null) return _cached;

        try
        {
            var asm = Assembly.GetExecutingAssembly();
            // Match on suffix rather than a hardcoded full resource id: the id is derived from
            // the default namespace + folder path, so a project rename would silently break a
            // literal lookup.
            var name = Array.Find(asm.GetManifestResourceNames(),
                n => n.EndsWith("md11_control_map.json", StringComparison.OrdinalIgnoreCase));

            if (name == null)
            {
                Log.Error("MD11", "md11_control_map.json embedded resource not found — MD-11 will have no controls.");
                return _cached = new Md11ControlMap();
            }

            using var stream = asm.GetManifestResourceStream(name);
            if (stream == null)
            {
                Log.Error("MD11", $"Could not open embedded resource {name} — MD-11 will have no controls.");
                return _cached = new Md11ControlMap();
            }

            var map = JsonSerializer.Deserialize<Md11ControlMap>(stream, Options) ?? new Md11ControlMap();
            Log.Info("MD11", $"Control map loaded: {map.Controls.Count} controls, {map.ExportVars.Count} export vars.");
            return _cached = map;
        }
        catch (Exception ex)
        {
            Log.Error("MD11", $"Failed to load md11_control_map.json: {ex.Message} — MD-11 will have no controls.");
            return _cached = new Md11ControlMap();
        }
    }
}

/// <summary>One clickable cockpit control, as emitted by TFDi's ModelBehaviorsExporter.</summary>
public sealed class Md11Control
{
    /// <summary>The node id, e.g. <c>MD11_OVHD_ELEC_GEN1_ARM_BT</c>. Also the MSFSBA variable key.</summary>
    [JsonPropertyName("node_id")]
    public string NodeId { get; set; } = string.Empty;

    /// <summary>
    /// button | knob | knob_pp | knob_push | switch | annun | guard | lever | handle.
    /// Drives how MSFSBA renders and writes the control — see <c>Md11Kinds</c>.
    /// </summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    [JsonPropertyName("template")]
    public string Template { get; set; } = string.Empty;

    /// <summary>Cockpit area label ("Overhead", "Pedestal", …) — becomes the panel section.</summary>
    [JsonPropertyName("area")]
    public string Area { get; set; } = "Other";

    /// <summary>Spoken label. TFDi's own tooltip wording where one exists, else derived from the node id.</summary>
    [JsonPropertyName("label")]
    public string? Label { get; set; }

    /// <summary>tooltip | derived | curated — provenance of <see cref="Label"/>.</summary>
    [JsonPropertyName("label_source")]
    public string LabelSource { get; set; } = string.Empty;

    /// <summary>The L:var carrying this control's state. Often, but not always, the node id itself.</summary>
    [JsonPropertyName("state_var")]
    public string StateVar { get; set; } = string.Empty;

    /// <summary>
    /// TFDi's own value→label map, lifted verbatim from the tooltip's RPN <c>%{case}</c> block.
    /// Keys are the raw numeric values as strings ("0", "20", "17.5"). Becomes ValueDescriptions.
    /// </summary>
    [JsonPropertyName("value_map")]
    public Dictionary<string, string> ValueMap { get; set; } = new();

    [JsonPropertyName("num_states")]
    public int? NumStates { get; set; }

    /// <summary>
    /// CEVENT ids keyed by field name (LEFT_BUTTON_DOWN, LEFT_BUTTON_UP, WHEEL_UP, WHEEL_DOWN,
    /// PUSH_DOWN, PULL_DOWN, …). Fired by writing the id to <c>L:CEVENT</c>.
    /// </summary>
    [JsonPropertyName("events")]
    public Dictionary<string, int> Events { get; set; } = new();

    [JsonPropertyName("guard_id")]
    public string? GuardId { get; set; }

    [JsonPropertyName("source")]
    public string Source { get; set; } = string.Empty;

    // ----- curated extras (see CURATED in the generator) -----

    /// <summary>
    /// Ordered detents, clean → fully extended. Present only where the generic tooltip parser
    /// cannot see the real positions — currently just the flap lever, whose Dial-A-Flap detent
    /// is an RPN RANGE test that <c>%{case}</c> parsing misses entirely.
    /// </summary>
    [JsonPropertyName("detents")]
    public List<Md11Detent>? Detents { get; set; }

    /// <summary>Present on the Dial-A-Flap thumbwheel only: the raw-units ↔ degrees transform.</summary>
    [JsonPropertyName("dial_a_flap")]
    public Md11DialAFlapSpec? DialAFlap { get; set; }

    [JsonPropertyName("notes")]
    public string? Notes { get; set; }

    /// <summary>The spoken label, never null — falls back to the node id so a control is always identifiable.</summary>
    public string DisplayLabel => string.IsNullOrWhiteSpace(Label) ? NodeId : Label!;

    public int? Event(string field) => Events.TryGetValue(field, out var v) ? v : null;
}

/// <summary>One position of a detented lever.</summary>
public sealed class Md11Detent
{
    /// <summary>The representative state-var value for this detent.</summary>
    [JsonPropertyName("value")]
    public double Value { get; set; }

    /// <summary>
    /// Inclusive [lo, hi] band of state-var values that count as this detent, when the detent is
    /// a RANGE rather than a point. The flap lever's Dial-A-Flap detent is [38, 65] — the handle
    /// sits anywhere in that band depending on the thumbwheel angle.
    /// </summary>
    [JsonPropertyName("range")]
    public List<double>? Range { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>True on the detent whose angle is set by the Dial-A-Flap thumbwheel.</summary>
    [JsonPropertyName("dial")]
    public bool Dial { get; set; }

    /// <summary>True when <paramref name="v"/> falls in this detent (range band if present, else near the point).</summary>
    public bool Matches(double v)
    {
        if (Range is { Count: 2 }) return v >= Range[0] && v <= Range[1];
        return Math.Abs(v - Value) < 0.5;
    }
}

/// <summary>
/// The Dial-A-Flap thumbwheel's raw↔degrees transform, from TFDi's own tooltip RPN
/// (<c>10 (L:MD11_DIALAFLAP_IND_RNG) 6.6667 / +</c>): degrees = 10 + raw / 6.6667,
/// so raw 0…100 spans the 10°…25° take-off flap range.
/// </summary>
public sealed class Md11DialAFlapSpec
{
    [JsonPropertyName("state_var")]
    public string StateVar { get; set; } = string.Empty;

    [JsonPropertyName("min_deg")]
    public double MinDeg { get; set; } = 10;

    [JsonPropertyName("max_deg")]
    public double MaxDeg { get; set; } = 25;

    [JsonPropertyName("units_per_deg")]
    public double UnitsPerDeg { get; set; } = 6.6667;

    /// <summary>Raw thumbwheel units → selected take-off flap angle in degrees.</summary>
    public double ToDegrees(double raw) => MinDeg + raw / UnitsPerDeg;

    /// <summary>Selected take-off flap angle in degrees → raw thumbwheel units.</summary>
    public double ToRaw(double degrees) => (degrees - MinDeg) * UnitsPerDeg;
}

/// <summary>The <c>kind</c> discriminator values used by the generator.</summary>
public static class Md11Kinds
{
    public const string Button = "button";
    public const string Knob = "knob";
    public const string KnobPushPull = "knob_pp";
    public const string KnobPush = "knob_push";
    public const string Switch = "switch";
    public const string Annunciator = "annun";
    public const string Guard = "guard";
    public const string Lever = "lever";
    public const string Handle = "handle";
}
