// Tests for ChangelogBuilder.ContributorMap — parses the machine-written
// `<pr>=<login>,<login>` map that tools/changelog-contributors.sh produces and
// ChangelogBuilder's --contributors option consumes.
//
// Malformed input is an ERROR, never silently skipped: the file is generated by a script,
// so a bad line means the script broke, and silent tolerance would misattribute entries.
// Graceful degradation (a PR that cannot be resolved) happens in the SCRIPT, by omitting
// the line — which is why "absent from the map" must render unattributed (renderer tests)
// while "present but malformed" must fail loudly (these).

using ChangelogBuilder;

namespace MSFSBlindAssist.Tests;

public class ContributorMapTests
{
    [Fact]
    public void Parse_reads_a_single_line()
    {
        var result = ContributorMap.Parse("184=robin24");

        Assert.True(result.Ok);
        Assert.Equal(["robin24"], result.Map[184]);
    }

    [Fact]
    public void Parse_reads_multiple_logins_preserving_order()
    {
        var result = ContributorMap.Parse("184=robin24,alice,bob");

        Assert.True(result.Ok);
        Assert.Equal(["robin24", "alice", "bob"], result.Map[184]);
    }

    [Fact]
    public void Parse_reads_multiple_lines()
    {
        var result = ContributorMap.Parse("184=robin24\n183=alice\n");

        Assert.True(result.Ok);
        Assert.Equal(2, result.Map.Count);
        Assert.Equal(["robin24"], result.Map[184]);
        Assert.Equal(["alice"], result.Map[183]);
    }

    [Fact]
    public void Parse_skips_blank_lines_and_comments()
    {
        var result = ContributorMap.Parse("# generated by changelog-contributors.sh\n\n184=robin24\n\n");

        Assert.True(result.Ok);
        Assert.Single(result.Map);
        Assert.Equal(["robin24"], result.Map[184]);
    }

    [Fact]
    public void Parse_tolerates_whitespace_around_tokens()
    {
        var result = ContributorMap.Parse("  184 = robin24 , alice  ");

        Assert.True(result.Ok);
        Assert.Equal(["robin24", "alice"], result.Map[184]);
    }

    [Fact]
    public void Parse_handles_windows_line_endings()
    {
        var result = ContributorMap.Parse("184=robin24\r\n183=alice\r\n");

        Assert.True(result.Ok);
        Assert.Equal(2, result.Map.Count);
    }

    [Fact]
    public void Parse_returns_empty_map_for_empty_content()
    {
        Assert.True(ContributorMap.Parse("").Ok);
        Assert.Empty(ContributorMap.Parse("").Map);
        Assert.True(ContributorMap.Parse("   \n  \n").Ok);
        Assert.Empty(ContributorMap.Parse("   \n  \n").Map);
    }

    [Fact]
    public void Parse_rejects_a_malformed_line_naming_its_line_number()
    {
        var result = ContributorMap.Parse("184=robin24\nnot-a-mapping\n");

        Assert.False(result.Ok);
        Assert.Contains(result.Errors, e => e.Contains("line 2"));
    }

    [Fact]
    public void Parse_rejects_a_duplicate_pr_number()
    {
        var result = ContributorMap.Parse("184=robin24\n184=alice\n");

        Assert.False(result.Ok);
        Assert.Contains(result.Errors, e => e.Contains("184"));
    }

    [Fact]
    public void Parse_rejects_an_empty_login_list()
    {
        Assert.False(ContributorMap.Parse("184=").Ok);
        Assert.False(ContributorMap.Parse("184=robin24,,alice").Ok);
    }

    [Fact]
    public void Parse_rejects_a_login_with_illegal_characters()
    {
        // The renderer adds the @ itself; a login containing one (or spaces) means the
        // generating script glitched.
        Assert.False(ContributorMap.Parse("184=@robin24").Ok);
        Assert.False(ContributorMap.Parse("184=rob in").Ok);
    }

    [Fact]
    public void Parse_rejects_a_leading_zero_pr_number()
    {
        // Same rule as the fragment filename grammar: PR numbers have no leading zero.
        Assert.False(ContributorMap.Parse("0184=robin24").Ok);
    }

    [Fact]
    public void Parse_collects_every_error_not_just_the_first()
    {
        var result = ContributorMap.Parse("bad-one\n184=robin24\nbad-two\n");

        Assert.False(result.Ok);
        Assert.Equal(2, result.Errors.Count);
    }
}
