#!/usr/bin/env python3
"""Generates the Synaptic A220 ECL data tables from the public ecl-editor sources.

Inputs (a checkout of https://github.com/synapticsim/ecl-editor):
  src/lib/vars.ts -> the ECL_VARIABLE enum: every cockpit state the aircraft's
                     Electronic Checklist can sense (switch positions, lever
                     detents, doors, fire handles...). Checklist package JSON
                     stores a sensed item's variable as the RAW NUMERIC INDEX
                     of this enum, so ORDER IS THE ABI — never reorder.
  src/lib/cas.ts  -> the CasMessage enum + CAS_MESSAGE_TEXT table: every crew
                     alerting message with its severity level and the official
                     display text. Non-normal checklists reference these; the
                     JSON again stores raw indices.

Output:
  MSFSBlindAssist/Aircraft/A220/SynapticA220EclData.cs

Usage:  python generate_a220_ecl.py <ecl-editor-dir> [<out.cs>]

Re-run against a fresh clone whenever Synaptic updates the editor (the enums
are expected to be append-only once the aircraft ships — a mid-list change on
their side would break every existing livery's checklist package too, so an
index shift in a regeneration diff is a red flag worth raising upstream, not
silently committing).

The generated file is data-only. Spoken labels for checklist items come from
the checklist package's own challenge/response text at runtime, not from
these names — the names exist to map a sensed index to the MSFSBA control
that satisfies it, and for logging/diagnostics.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

DEFAULT_OUT = Path(__file__).resolve().parents[2] / "MSFSBlindAssist" / "Aircraft" / "A220" / "SynapticA220EclData.cs"


def parse_enum(source: str, enum_name: str) -> list[str]:
    """Extracts member names, in order, from a TS enum with no explicit values."""
    m = re.search(rf"export enum {enum_name} \{{(.*?)^\}}", source, re.S | re.M)
    if not m:
        raise SystemExit(f"enum {enum_name} not found")
    members: list[str] = []
    for line in m.group(1).splitlines():
        line = line.split("//")[0].strip().rstrip(",")
        if not line:
            continue
        if "=" in line:
            raise SystemExit(f"{enum_name}.{line}: explicit value — sequential-index assumption broken, refusing to generate")
        if not re.fullmatch(r"[A-Za-z0-9_]+", line):
            raise SystemExit(f"{enum_name}: unparseable member line: {line!r}")
        members.append(line)
    return members


def parse_cas_text(source: str) -> dict[str, tuple[str, str]]:
    """Extracts CAS_MESSAGE_TEXT: member name -> (level, official display text)."""
    m = re.search(r"export const CAS_MESSAGE_TEXT[^{]*\{(.*?)^\};", source, re.S | re.M)
    if not m:
        raise SystemExit("CAS_MESSAGE_TEXT not found")
    entries: dict[str, tuple[str, str]] = {}
    for name, level, text in re.findall(
        r"\[CasMessage\.(\w+)\]:\s*\[MessageLevel\.(\w+),\s*\"((?:[^\"\\]|\\.)*)\"\]", m.group(1)
    ):
        entries[name] = (level, text.replace('\\"', '"'))
    return entries


def cs_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    src_dir = Path(sys.argv[1]) / "src" / "lib"
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT

    vars_ts = (src_dir / "vars.ts").read_text(encoding="utf-8")
    cas_ts = (src_dir / "cas.ts").read_text(encoding="utf-8")

    ecl_vars = parse_enum(vars_ts, "ECL_VARIABLE")
    cas_members = parse_enum(cas_ts, "CasMessage")
    cas_text = parse_cas_text(cas_ts)
    levels = parse_enum(cas_ts, "MessageLevel")
    if levels != ["Status", "Advisory", "Caution", "Warning"]:
        raise SystemExit(f"MessageLevel changed upstream: {levels} — update A220CasLevel to match before regenerating")

    missing = [m for m in cas_members if m not in cas_text]
    if missing:
        raise SystemExit(f"CAS members without a CAS_MESSAGE_TEXT entry: {missing}")
    orphans = set(cas_text) - set(cas_members)
    if orphans:
        raise SystemExit(f"CAS_MESSAGE_TEXT entries not in the enum: {sorted(orphans)}")

    lines: list[str] = []
    a = lines.append
    a("// <auto-generated>")
    a("// Generated by tools/a220-gen/generate_a220_ecl.py from the Synaptic ecl-editor sources")
    a("// (https://github.com/synapticsim/ecl-editor: src/lib/vars.ts + src/lib/cas.ts).")
    a("// Do not hand-edit — regenerate against a fresh clone instead.")
    a("//")
    a("// ORDER IS THE ABI: A220 checklist package JSON stores sensed variables and CAS")
    a("// references as raw indices into these tables. Never reorder; upstream is expected")
    a("// to be append-only post-release (a reorder would break their own liveries too).")
    a("// </auto-generated>")
    a("")
    a("namespace MSFSBlindAssist.Aircraft.A220;")
    a("")
    a("/// <summary>Severity level of an A220 crew alerting (CAS) message.</summary>")
    a("public enum A220CasLevel")
    a("{")
    for lv in levels:
        a(f"    {lv},")
    a("}")
    a("")
    a("/// <summary>One A220 CAS message: enum name, severity, and the official display text.</summary>")
    a("public readonly struct A220CasMessage(string name, A220CasLevel level, string text)")
    a("{")
    a("    public string Name { get; } = name;")
    a("    public A220CasLevel Level { get; } = level;")
    a("    public string Text { get; } = text;")
    a("}")
    a("")
    a("/// <summary>")
    a("/// Data tables for the Synaptic A220's Electronic Checklist (ECL) and CAS systems,")
    a("/// mirrored from the public checklist-editor sources. A sensed checklist item's")
    a("/// <c>sensed</c> field in package JSON is an index into <see cref=\"EclVariableNames\"/>;")
    a("/// a non-normal checklist's <c>cas</c> field is an index into <see cref=\"CasMessages\"/>.")
    a("/// </summary>")
    a("public static class SynapticA220EclData")
    a("{")
    a(f"    /// <summary>The {len(ecl_vars)} sensed cockpit states, indexed by ECL_VARIABLE value.</summary>")
    a("    public static readonly string[] EclVariableNames =")
    a("    [")
    for name in ecl_vars:
        a(f"        {cs_str(name)},")
    a("    ];")
    a("")
    a(f"    /// <summary>The {len(cas_members)} CAS messages, indexed by CasMessage value.</summary>")
    a("    public static readonly A220CasMessage[] CasMessages =")
    a("    [")
    for name in cas_members:
        level, text = cas_text[name]
        a(f"        new({cs_str(name)}, A220CasLevel.{level}, {cs_str(text)}),")
    a("    ];")
    a("")
    a("    /// <summary>Name of a sensed ECL variable index, or null if out of range.</summary>")
    a("    public static string? EclVariableName(int index) =>")
    a("        index >= 0 && index < EclVariableNames.Length ? EclVariableNames[index] : null;")
    a("")
    a("    /// <summary>CAS message for an index, or null if out of range.</summary>")
    a("    public static A220CasMessage? CasMessage(int index) =>")
    a("        index >= 0 && index < CasMessages.Length ? CasMessages[index] : null;")
    a("}")
    a("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{out_path}: {len(ecl_vars)} ECL variables, {len(cas_members)} CAS messages")


if __name__ == "__main__":
    main()
